version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ceciestunmotdepasse
    volumes:
      - ./data:/data/db

  back:
    build: ./back
    restart: always
    ports:
      - 8000:8080
    environment:
      PORT: 8080
      MONGO_USER: root
      MONGO_PASSWORD: ceciestunmotdepasse
      MONGO_FULL_HOSTNAME: mongo:27017
    depends_on:
      - mongo

  front:
    build: ./front
    restart: always
    ports:
      - 80:80
    depends_on:
      - back
